---

- hosts: prod
  sudo: yes 

  tasks:
  - name: Install Apache Packages on Debian OS
    apt: name=apache2 state=present
    when: ansible_os_family == "Debian" 

  - name: Start Apache Service on Debian OS
    service: name=apache2 state=started 
    when: ansible_os_family == "Debian"
 
  - name: Install Apache Packages on RedHat Family
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Start Apache Service on RedHat Family
    service: name=httpd state=started 
    when: ansible_os_family == "RedHat"

  - name: Deploy Custom Index Page
    copy: src=templates/index.html dest=/var/www/html/abc.html 
